configs:
  groupUSD: true # combine all USD stablecoins into USDT
exchanges:
  - name: binance
    initParams:
      apiKey:
      secret:
  - name: okex
    initParams:
      apiKey:
      secret:
      password:
erc20:
  addresses:
    - "0xb5dd722b87c129dd9e18bd53122c2e1d957cae43"
    - ""
btc:
  addresses:
    - ""
sol:
  addresses:
    - ""
doge:
  addresses:
    - ""

others:
  - symbol: USDT
    amount: 1000
