configs:
  groupUSD: true # combine all USD stablecoins into USDT
exchanges:
  - name: binance
    initParams:
      apiKey: # readonly api key
      secret:
  - name: okex
    initParams:
      apiKey: # readonly api key
      secret:
      password:
erc20:
  addresses:
    - ""
btc:
  addresses:
    - ""
sol:
  addresses:
    - ""
doge:
  addresses:
    - ""

others:
  - symbol: USDT
    amount: 1000
