CREATE TABLE IF NOT EXISTS assets (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	top01 TEXT,
	amount01 REAL,
	value01 REAL,
	top02 TEXT,
	amount02 REAL,
	value02 REAL,
	top03 TEXT,
	amount03 REAL,
	value03 REAL,
	top04 TEXT,
	amount04 REAL,
	value04 REAL,
	top05 TEXT,
	amount05 REAL,
	value05 REAL,
	top06 TEXT,
	amount06 REAL,
	value06 REAL,
	top07 TEXT,
	amount07 REAL,
	value07 REAL,
	top08 TEXT,
	amount08 REAL,
	value08 REAL,
	top09 TEXT,
	amount09 REAL,
	value09 REAL,
	top10 TEXT,
	amount10 REAL,
	value10 REAL,
	topOthers TEXT,
	amountOthers TEXT,
	valueOthers REAL,
	total REAL
);
