CREATE TABLE IF NOT EXISTS assets_v2 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	uuid TEXT NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	symbol TEXT NOT NULL,
	amount REAL NOT NULL,
	value REAL NOT NULL,
	price REAL  NOT NULL
);
