CREATE TABLE IF NOT EXISTS chat_sessions (
  id TEXT NOT NULL PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pinned INTEGER NOT NULL DEFAULT 0,
  messageCount INTEGER NOT NULL DEFAULT 0,
  preview TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS chat_sessions_pinned_updated_idx
  ON chat_sessions (pinned DESC, updatedAt DESC);
