CREATE TABLE IF NOT EXISTS transactions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	wallet TEXT NOT NULL,
	symbol TEXT NOT NULL,
	amount REAL NOT NULL,
	price REAL NOT NULL,
	-- txnType: BUY, SELL, DEPOSIT, WITHDRAW
	txnType TEXT NOT NULL,
	txnCreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
